import ClientOnly from '@/components/ClientOnly'
import Navbar from '@/components/navbar/Navbar'
import type { Metadata } from 'next'
import { Suspense } from 'react'
import './globals.css'

export const metadata: Metadata = {
	title: 'Pet Tasker',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
	modal,
}: {
	children: React.ReactNode
	modal: React.ReactNode
}) {
	return (
		<html className='h-full bg-white'>
			<body className='h-full'>
				{modal}
				<Suspense fallback={<div></div>}>
					<ClientOnly />
				</Suspense>
				<Navbar />
				{children}
			</body>
		</html>
	)
}
